// 
// If you have a form like this:
//
//     <form id="trainer">
//        <span id="given_phrase">Some phrase probably generated by the server</span>
//        <input type="text" class="phrase" />
//      </form>

//Assuming cadence.js is already loaded.
jQuery(document).ready(function ($) {
  $("form#trainer").cadence(function (result) {
    /*
     * I'm a user supplied callback function.
     */
    console.log(result);
  });
});

